on:
  pull_request:
    branches:
      - main

  workflow_dispatch:
  
jobs:
  test:
    name: Tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup env
        run: corepack enable 
      - name: Install deps
        run: |
          yarn install
          yarn build
      - name: Run tests
        run: yarn test
          
